### ISSUE TITLE
Add job filter for "Blackbox exporter - ICMP" dashboard

### ISSUE THREAD

**Issue by Debcharon** [M0NsTeRRR/grafana-dashboards#1]
**What would you like to be added**: 

Add job filter for "Blackbox exporter - ICMP" dashboard

**Why is this needed**:

I've multiple jobs to monitor.

```yaml
  - job_name: "icmp_job1"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
    - files:
      - 'services/icmp_job1.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      # - source_labels: [__param_target]
        # target_label: instance
      - target_label: __address__
        replacement: hostname1:9115

  - job_name: "icmp_job2"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
    - files:
      - 'services/icmp_job2.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      # - source_labels: [__param_target]
        # target_label: instance
      - target_label: __address__
        replacement: hostname2:9115
```

**How to implement this work**:

Add new variable "job"
| Variable | Definition                                                      |
| -------- | --------------------------------------------------------------- |
| job      | label_values(probe_icmp_duration_seconds,job)                   |
| instance | label_values(probe_icmp_duration_seconds{job=~"$job"},instance) |

PromQL

ICMP RTT: `sum(probe_icmp_duration_seconds{phase="rtt",job=~"$job",instance=~"$instance"}) by (instance)`
ICMP packet loss: `1-probe_success{job=~"$job",instance=~"$instance"}`
ICMP $instance: 
A: `1-avg_over_time(probe_success{job=~"$job",instance=~"$instance"}[$__interval])`
B: `probe_icmp_duration_seconds{phase="rtt",job=~"$job",instance=~"$instance"} > 0`
