### ISSUE TITLE
PowerDNS Recursor Grafana dashboard is listing authoritative servers only

### ISSUE THREAD

**Issue by jsabater** [M0NsTeRRR/grafana-dashboards#3]
Hey! I am using PowerDNS Recursor 5.1.3 on Debian 12 Bookworm and I have enabled the webserver to access its `/metrics` endpoint. I have configured Prometheus 2.55.1 as follows:

```yaml
  # PowerDNS Authoritative
  - job_name: 'pdns_auth'
    scrape_interval: 1m
    scheme: https
    proxy_from_environment: false
    metrics_path: /metrics
    tls_config:
      ca_file: /etc/ssl/certs/ISRG_Root_X1.pem
      insecure_skip_verify: false
    file_sd_configs:
      - files:
        - file_sd_configs/pdns_metrics/pdns_auth.yml

  # PowerDNS Recursor
  - job_name: 'pdns_rec'
    scrape_interval: 1m
    scheme: https
    proxy_from_environment: false
    metrics_path: /metrics
    tls_config:
      ca_file: /etc/ssl/certs/ISRG_Root_X1.pem
      insecure_skip_verify: false
    file_sd_configs:
      - files:
        - file_sd_configs/pdns_metrics/pdns_rec.yml
```

The contents of the files inside `file_sd_configs/pdns_metrics/` are:

```yaml
# pdns_auth.yml
- targets:
  - 'pdns3.domain.com:8080'
  - 'pdns5.domain.com:8080'
  labels:
    group: 'pdns_auth'

# pdns_rec.yml
- targets:
  - 'pdns4.domain.com:8080'
  - 'pdns6.domain.com:8080'
  labels:
    group: 'pdns_rec'
```

That is four separate LXC in my Proxmox cluster. The respective webservers are configured on port 8081 and NGINX is configured on port 8080 to act as reverse proxy to provide TLS encrypted communications.

Prometheus is accessing and scrapping the targets alright. At least, I see no errors.

Then I am using Grafana 11.4 to visualise data, and I am using both your dashboards. I downloaded the latest versions of them and imported them using my Prometheus data source. But only the authoritative dashboard is showing data. The recursor dashboard is, actually, only listing the authoritative servers (pdns3 and pdns5), same as the authoritative dashboard.

Could you please check it out? Please let me know if I can be of any help.

Thanks.
