### ISSUE TITLE
MetalLB: Datasource ${DS_PROMETHEUS} was not found

### ISSUE THREAD

**Issue by mcsrobert** [M0NsTeRRR/grafana-dashboards#4]
**What happened**: I'm using [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md) to install and configure Prometheus and Grafana. In the Helm chart, I've configured various dashboards to be automatically installed:

```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      longhorn:
        gnetId: 16888
        revision: 9
      metallb:
        gnetId: 20162
        revision: 6
      traefik:
        gnetId: 17346
        revision: 9
```

However, this result in:

<img width="559" alt="Image" src="https://github.com/user-attachments/assets/455b9ebf-bb4d-4b81-9eeb-9550dc61e142" />

**What you expected to happen**: Expected this to work too, as the dashboards for Traefik and Longhorn work without any issues.

**How to reproduce it (as minimally and precisely as possible)**: Might be a bit tricky, as this involves a K8s cluster, but see the config above. I've also had a quick look to see if I saw any obvious differences between this chart and the other two, but I'm not familiar enough with Grafana dashboards to spot any obvious errors.

**Anything else we need to know?**: Happy to help further troubleshoot this however I can. :)

**Environment and application version**: Grafana 11.5.1

**Comment by M0NsTeRRR** [comment]
I assume your prometheus datasource is named `Prometheus` when the default value in my dashboard is `prometheus`

Traefik
```
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "Prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
[...]
```

Metallb
```
"__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ]
[...]
```

You can override the value like I do in my homelab https://github.com/M0NsTeRRR/homelabv3-infra/blob/main/argocd/monitoring/grafana/values.yaml#L91
```
  dashboards:
      metallb:
        gnetId: 20162
        revision: 6
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
```
This should work :)

Regards,
